apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetragon-logging
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "tetragon"
    repoURL: https://github.com/omerurhan/banzai-logging-conf.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true