{{- if .Values.logging.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 5.3.1
    helm:
      values: |
        global:
          dnsService: "rke2-coredns-rke2-coredns"
        rbac:
          pspEnabled: false
        backend:
          replicas: 3
          persistence:
            size: 1Gi
        gateway:
          replicas: 1
          basicAuth:
            enabled: false
          autoscaling:
            enabled: false
          ingress:
            enabled: true
            hosts:
              - host: loki-demo.mooo.com
                paths:
                  - path: /
                    pathType: Prefix
            ingressClassName: 'nginx'
            tls: []
        loki:
          auth_enabled: false
          storage:
            bucketNames:
              chunks: rke2-loki-logging-bucket
              ruler: rke2-loki-logging-bucket
              admin: rke2-loki-logging-bucket
            s3:
              region: eu-central-1
            type: s3
        read:
          replicas: 3
          persistence:
            size: 1Gi
        write:
          replicas: 3
          persistence:
            size: 1Gi
        monitoring:
          lokiCanary:
            enabled: false
    chart: loki
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end }}